### ISSUE TITLE
98169

### ISSUE THREAD

**Issue by stephan3321** [sttng/LDD-New-Parts#2]
I think it would be better to make the "neck" parts 1 mesh, so the left and right side are always colored the same. And, besides that, the ring of spikes should be a seperate mesh as well, if possible.

**Comment by sttng** [comment]
I'll look into it. In general I just take what is there from Unity and just take it over 1:1 as much as possible. Having said that I agree with your feedback. 

I will use this one as a reference:
https://jaysbrickblog.com/wp-content/uploads/2019/06/LEGO-75937-Triceratops-Rampage-Triceratops-Comparison.jpg
https://jaysbrickblog.com/wp-content/uploads/2019/06/LEGO-75937-Triceratops-Rampage-LEGO-Triceratops-Side-View.jpg

I think this part is currently kind of useless, as we miss the body and legs.

**Comment by sttng** [comment]
Ok I fixed it. I didn't change the ring of spikes (yet), because as shown on the pictures this is a print and not a mold. Not sure if I should change it.

**Comment by sttng** [comment]
Ok I separated the ring of spikes. Reason being: Even if its a print, to make it decoratable one would most likely have to separate this as well (it's not decoratable yet).

**Comment by stephan3321** [comment]
Awesome! Only 1 spike is missing from the "spikes mesh". When seen from the front; it's the most right one.
